-- Clear all existing data
DELETE FROM transactions;
DELETE FROM loans;
DELETE FROM profiles;
DELETE FROM faqs;

-- Insert comprehensive banking FAQs
INSERT INTO faqs (question, answer, category, keywords) VALUES
('What types of loans does EBL offer?', 'EBL offers various types of loans including:\n\n1. **Personal Loans** - For personal needs, medical expenses, travel, etc.\n2. **Home Loans** - For purchasing or constructing residential properties\n3. **Car Loans** - For purchasing new or used vehicles\n4. **Business Loans** - For business expansion, working capital, equipment\n5. **Education Loans** - For higher education expenses\n6. **SME Loans** - For small and medium enterprises\n\nWhich type of loan are you interested in? I can provide more details about any specific loan type.', 'loans', ARRAY['loan', 'personal loan', 'home loan', 'car loan', 'business loan', 'education loan', 'sme loan']),

('What types of accounts can I open at EBL?', 'EBL offers several account types to meet your banking needs:\n\n1. **Savings Account** - Earn interest on your deposits\n2. **Current Account** - For businesses and frequent transactions\n3. **Fixed Deposit Account** - Higher interest rates for fixed terms\n4. **Student Account** - Special benefits for students\n5. **Senior Citizen Account** - Special benefits for senior citizens\n6. **Salary Account** - For salaried employees\n7. **NRB Account** - For non-resident Bangladeshis\n\nWhich account type interests you? I can provide detailed information about any specific account.', 'accounts', ARRAY['account', 'savings account', 'current account', 'fixed deposit', 'student account', 'senior citizen', 'salary account', 'nrb account']),

('What are the interest rates for different accounts?', 'Our current interest rates are:\n\n**Savings Account:** 4.5% - 5.5% per annum\n**Fixed Deposit:** 6% - 8% per annum (depending on tenure)\n**Current Account:** No interest\n**Student Account:** 5% per annum\n**Senior Citizen Account:** 6% per annum\n\nRates may vary based on account balance and tenure. Would you like details about any specific account type?', 'interest rates', ARRAY['interest', 'rate', 'savings', 'fixed deposit', 'fd']),

('How can I apply for a credit card?', 'To apply for an EBL credit card:\n\n1. **Eligibility:** Age 21-65, minimum income BDT 25,000\n2. **Documents needed:**\n   - Copy of NID/Passport\n   - Salary certificate/Income proof\n   - Bank statements (last 3 months)\n   - Passport size photographs\n\n3. **Application process:**\n   - Visit any EBL branch\n   - Fill application form\n   - Submit required documents\n   - Wait for approval (7-10 working days)\n\nWe offer various credit card types. Which type interests you - Classic, Gold, or Platinum?', 'credit cards', ARRAY['credit card', 'apply', 'application', 'classic', 'gold', 'platinum']),

('What are the charges for different banking services?', 'Here are our key service charges:\n\n**ATM Services:**\n- Own ATM: Free\n- Other bank ATM: BDT 15 per transaction\n\n**Online Banking:** Free\n**Mobile Banking:** Free registration, minimal transaction fees\n**Cheque Book:** BDT 200 for 25 leaves\n**Account Maintenance:** Varies by account type\n**SWIFT Transfer:** BDT 1,500 + correspondent charges\n\nWould you like detailed charges for any specific service?', 'charges', ARRAY['charges', 'fees', 'atm', 'online banking', 'mobile banking', 'cheque book', 'swift']),

('How do I activate mobile banking?', 'To activate EBL mobile banking:\n\n1. **Download** EBL mobile app from Play Store/App Store\n2. **Registration:**\n   - Enter your account number\n   - Provide mobile number (registered with bank)\n   - Create PIN\n3. **Verification:** You''ll receive OTP for verification\n4. **Activation:** Complete registration process\n\n**Features available:**\n- Balance inquiry\n- Fund transfer\n- Bill payments\n- Mobile recharge\n- Mini statements\n\nNeed help with any specific mobile banking feature?', 'mobile banking', ARRAY['mobile banking', 'app', 'activation', 'registration', 'transfer', 'bill payment']),

('What documents do I need to open an account?', 'Required documents for account opening:\n\n**For Individual Accounts:**\n- Original NID/Passport + photocopy\n- Recent passport size photographs (2 copies)\n- Utility bill/rental agreement (address proof)\n- Initial deposit (varies by account type)\n\n**For Business Accounts:**\n- Trade license\n- Memorandum & Articles of Association\n- Board resolution\n- Authorized signatories'' documents\n- TIN certificate\n\n**Minimum deposit requirements vary by account type.** Which type of account are you planning to open?', 'documents', ARRAY['documents', 'account opening', 'nid', 'passport', 'requirements', 'business account']),

('How can I transfer money internationally?', 'EBL offers international money transfer through:\n\n**1. SWIFT Wire Transfer:**\n- Send money to any bank worldwide\n- Charges: BDT 1,500 + correspondent bank charges\n- Time: 1-3 working days\n\n**2. Western Union:**\n- Quick cash pickup worldwide\n- Competitive exchange rates\n- Time: Minutes to hours\n\n**3. Money Gram:**\n- Global money transfer service\n- Multiple pickup options\n\n**Required:** Valid reason for transfer, beneficiary details, proper documentation\n\nWhich transfer method would you prefer?', 'international transfer', ARRAY['international', 'transfer', 'swift', 'western union', 'money gram', 'remittance']),

('What are the loan eligibility criteria?', 'General loan eligibility criteria:\n\n**Age:** 21-65 years\n**Income:** Minimum varies by loan type\n**Employment:** Stable job/business (min 1 year)\n**Credit Score:** Good credit history required\n\n**Specific criteria by loan type:**\n- **Personal Loan:** Min income BDT 30,000\n- **Home Loan:** Min income BDT 50,000\n- **Car Loan:** Min income BDT 40,000\n- **Business Loan:** Min business age 2 years\n\n**Documents needed:** Income proof, bank statements, collateral documents (if any)\n\nWhich loan type are you considering? I can provide specific eligibility details.', 'loan eligibility', ARRAY['eligibility', 'criteria', 'income', 'age', 'employment', 'personal loan', 'home loan', 'car loan']),

('How do I report a lost or stolen card?', 'To report lost/stolen debit or credit card:\n\n**Immediate Steps:**\n1. **Call EBL 24/7 hotline:** 16236\n2. **Visit nearest branch** with proper ID\n3. **File written complaint**\n\n**Card will be blocked immediately** to prevent misuse\n\n**Replacement card:**\n- Issued within 7 working days\n- Charges: BDT 500 for debit card, BDT 1,000 for credit card\n- Emergency card available (additional charges apply)\n\n**Important:** Report immediately to avoid liability for unauthorized transactions.', 'lost card', ARRAY['lost card', 'stolen card', 'block card', 'replacement', 'hotline', 'emergency']),

('What are EBL''s digital banking services?', 'EBL offers comprehensive digital banking:\n\n**1. Internet Banking:**\n- Account management\n- Fund transfers\n- Bill payments\n- Statement downloads\n\n**2. Mobile Banking App:**\n- All internet banking features\n- QR code payments\n- Cardless ATM withdrawal\n\n**3. SMS Banking:**\n- Balance inquiry\n- Mini statements\n- Transaction alerts\n\n**4. ATM Services:**\n- 24/7 cash withdrawal\n- Balance inquiry\n- Mini statements\n\n**5. Agent Banking:**\n- Banking services at your doorstep\n- Cash deposit/withdrawal\n\nWhich digital service would you like to know more about?', 'digital banking', ARRAY['digital banking', 'internet banking', 'mobile app', 'sms banking', 'atm', 'agent banking']),

('How do I close my bank account?', 'To close your EBL account:\n\n**Steps:**\n1. **Visit branch** where account was opened\n2. **Bring required documents:**\n   - Account closure form\n   - Original NID/Passport\n   - Unused cheque leaves\n   - Debit/credit cards\n3. **Clear all dues** (loan, card, charges)\n4. **Withdraw remaining balance**\n\n**Processing time:** 1-2 working days\n**Charges:** May apply if account maintained for less than 1 year\n\n**Note:** Ensure all auto-debits are cancelled before closure\n\nNeed help with any specific aspect of account closure?', 'account closure', ARRAY['close account', 'account closure', 'terminate', 'cancel account']);