-- Add 11 new FAQs including card services and other banking topics
INSERT INTO public.faqs (question, answer, keywords, category) VALUES
('What are the card services?', 'Eastern Bank offers comprehensive card services: 1) Debit Cards: Visa/Mastercard with ATM, POS, and online transaction facilities 2) Credit Cards: Various categories including Classic, Gold, Platinum with cashback and reward points 3) Prepaid Cards: For controlled spending and gifting 4) Corporate Cards: For business expenses 5) Student Cards: Special rates for students 6) Card Security: 24/7 fraud monitoring, SMS alerts, and instant card blocking via mobile app or hotline 16236.', ARRAY['card', 'debit', 'credit', 'services', 'visa', 'mastercard', 'prepaid'], 'Card Services'),

('How to report a lost or stolen card?', 'To report lost/stolen card: 1) Call our 24/7 hotline 16236 immediately 2) Use Mobile Banking App - go to Card Services > Block Card 3) Visit nearest branch with NID 4) Online Banking - Login > Card Management > Block Card. Your card will be blocked instantly to prevent misuse. Replacement card will be issued within 3-5 working days.', ARRAY['lost card', 'stolen card', 'block card', 'report', 'emergency'], 'Card Services'),

('What are the foreign exchange rates today?', 'Current foreign exchange rates (indicative): USD 1 = ৳109.50, EUR 1 = ৳118.75, GBP 1 = ৳138.20, SAR 1 = ৳29.15, AED 1 = ৳29.85. Rates are updated multiple times daily. For live rates and currency exchange, visit any branch or check our mobile app. We offer competitive rates for remittance and foreign currency exchange.', ARRAY['exchange rate', 'forex', 'usd', 'euro', 'pound', 'foreign currency', 'remittance'], 'Foreign Exchange'),

('How to get a bank statement?', 'You can get bank statements through: 1) Mobile Banking App - Account > Statements > Select period and download PDF 2) Internet Banking - Account Summary > Download Statement 3) ATM - Select Mini Statement option 4) Branch visit with account details 5) Request via SMS by sending STMT<space>Account Number to 16236. Statements available for up to 2 years.', ARRAY['statement', 'account statement', 'download', 'transaction history', 'pdf'], 'Account Services'),

('What are the minimum balance requirements?', 'Minimum balance requirements: Current Account - ৳10,000, Savings Account - ৳5,000, Student Account - ৳1,000, Senior Citizen Account - ৳2,000, Salary Account - ৳1,000, Premium Account - ৳100,000. Charges apply if balance falls below minimum: ৳200-500 depending on account type. Maintain required balance to avoid charges.', ARRAY['minimum balance', 'charges', 'account types', 'balance requirement'], 'Account Services'),

('How to apply for a checkbook?', 'To apply for checkbook: 1) Visit any branch with account details and NID 2) Fill checkbook application form 3) Pay applicable charges (৳150-300 depending on account type) 4) Checkbook ready in 2-3 working days 5) Also apply via Mobile Banking App > Services > Checkbook Request. Maximum 50 leaves per checkbook. Handle with care and report immediately if lost.', ARRAY['checkbook', 'cheque book', 'apply', 'request', 'charges'], 'Account Services'),

('What are the investment options available?', 'Investment options at Eastern Bank: 1) Fixed Deposits: 5.5%-7.5% return based on tenure 2) DPS (Monthly Savings): 6%-8% annual return 3) Mutual Funds: Equity and bond funds 4) Government Bonds: 4%-6% secure returns 5) Corporate Bonds: Higher returns with moderate risk 6) Foreign Currency Deposits: USD, EUR deposits 7) Gold Investment Scheme. Consult our investment advisors for personalized portfolio.', ARRAY['investment', 'fixed deposit', 'dps', 'mutual fund', 'bonds', 'portfolio'], 'Investment Services'),

('How to activate SMS banking?', 'To activate SMS Banking: 1) Send ACT<space>Account Number to 16236 2) Visit branch with NID and account details 3) Use Mobile Banking App > Settings > SMS Services 4) Call 16236 and request activation. Once active, get balance by sending BAL to 16236, mini statement by sending STMT, and transaction alerts automatically. Charges: ৳3 per SMS.', ARRAY['sms banking', 'activate', 'text banking', 'balance inquiry', 'alerts'], 'Mobile Banking'),

('What are the education loan benefits?', 'Education Loan benefits: 1) No collateral required up to ৳500,000 2) Competitive interest rates starting from 8% 3) Flexible repayment terms up to 10 years 4) Moratorium period during study + 6 months 5) Covers tuition fees, accommodation, books, laptop 6) Available for local and international education 7) Quick processing within 7-10 days 8) Parent/guardian as co-applicant accepted.', ARRAY['education loan', 'student loan', 'study', 'benefits', 'moratorium', 'collateral'], 'Loan Services'),

('How to open a joint account?', 'To open joint account: 1) All account holders must be present during opening 2) Required documents: NID/Passport of all holders, photographs, nominee details 3) Choose operation type: Either or Survivor, Joint operation required 4) Minimum deposit as per account type 5) All holders get separate debit cards and checkbooks 6) Any holder can operate account unless restrictions specified 7) Account accessible via mobile/internet banking by all holders.', ARRAY['joint account', 'multiple holders', 'either or survivor', 'operation', 'family account'], 'Account Opening'),

('What are the business banking services?', 'Business Banking services: 1) Current Account with overdraft facility 2) Trade Finance: LC, Bank Guarantee, Bill Discounting 3) Cash Management: Collection services, payroll management 4) Business Loans: Term loans, working capital, equipment financing 5) Corporate Cards for expense management 6) Treasury Services: Foreign exchange, hedging 7) Online Business Banking platform 8) Dedicated relationship manager for businesses above ৳10 crore turnover.', ARRAY['business banking', 'trade finance', 'cash management', 'corporate', 'overdraft', 'working capital'], 'Business Services');