// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovxqfifzkycyfacdkpue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92eHFmaWZ6a3ljeWZhY2RrcHVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NjcxODMsImV4cCI6MjA2NzQ0MzE4M30.XmjLOZ5Nb7bQLV1VlNqL6Y9kAJK0m2fcj7vuJsTMhVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});